### ISSUE TITLE
If a model is inherited from a super type then validation constraints on structural features in the super type are not reported by the "validation/constraints" endpoint

### ISSUE THREAD

**Issue by awillemsen** [eclipse-emfcloud/emfcloud-modelserver#109]
See attached file.
[super_constraints.txt](https://github.com/eclipse-emfcloud/emfcloud-modelserver/files/6421110/super_constraints.txt)

**Comment by sgraband** [comment]
Thanks for reporting and the detailed report :+1: 

I already implemented a similar behavior into #103. The DefaultValidator will now recursively look for all constraints of parent elements as well (and hide data types that do not contain any constraints to keep the size of the result small).

**Comment by sgraband** [comment]
@awillemsen 
#103 is now merged. And should cover your use case.

**Comment by awillemsen** [comment]
@sgraband Thanks, Simon.  I noticed the merge, and have already tested the changes - both the validation constraints change, and the fix for the exception raised when validating patterns, do indeed satisfy our requirements.  Much appreciated :-)
