### ISSUE TITLE
when "mvn clean install" , InterpolationException happen

### ISSUE THREAD

**Issue by davidxwwang** [eclipse-emfcloud/emfcloud-modelserver#149]
when "mvn clean install"  the error happen :  org.eclipse.emfcloud.modelserver.coffee.model: Execution default-jar of goal org.apache.maven.plugins:maven-jar-plugin:2.4:jar failed: A required class was missing while executing org.apache.maven.plugins:maven-jar-plugin:2.4:jar: org/codehaus/plexus/interpolation/InterpolationException

**Comment by martin-fleck-at** [comment]
@davidxwwang Thank you for your report. Unfortunately, I cannot reproduce this locally or on the CI (I started a build here: https://ci.eclipse.org/emfcloud/job/eclipse-emfcloud/job/emfcloud-modelserver/job/master/79/). Are you working on the current master? Which version of maven are you using? Locally I tried with 3.6.3 and on the CI we use 3.8.3.

**Comment by davidxwwang** [comment]
thanks a lot ,l use maven 3.6.3 and master branch,it is not maven problem,maybe some plugin is not downloaded, l will try later

**Comment by martin-fleck-at** [comment]
@davidxwwang Do you still have troubles with maven or did you manage to resolve the issue?

**Comment by davidxwwang** [comment]
@martin-fleck-at thanks, after l copy the plugin and dependency from others it ok now, but when l convert the EMF xml file to the json type ,seemly not converted successfully(only has the "eClass" property, other properties is losted),  so l donot know why.
 the original xml file :
`<?xml version="1.0" encoding="UTF-8"?>
<AUTOSAR xmlns="http://autosar.org/schema/r4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://autosar.org/schema/r4.0 AUTOSAR_00049.xsd">
  <AR-PACKAGES>
    <AR-PACKAGE UUID="6ad69a4a-9da9-49aa-b75b-c99cfebaa0b6">
      <SHORT-NAME>ARRoot</SHORT-NAME>
      <AR-PACKAGES>
        <AR-PACKAGE>
          <SHORT-NAME>P1</SHORT-NAME>
          <ELEMENTS>
            <BSW-MODULE-DESCRIPTION>
              <SHORT-NAME>des1</SHORT-NAME>
            </BSW-MODULE-DESCRIPTION>
          </ELEMENTS>
        </AR-PACKAGE>
      </AR-PACKAGES>
    </AR-PACKAGE>
  </AR-PACKAGES>
</AUTOSAR>`

but when  its converted json form is , some data is disappeared, its json form data is :
`{"jsonrpc":"2.0","id":1,"result":{"body":{"eClass":"http://autosar.org/schema/r4.0/autosar40/atls#//AUTOSAR"},"statusCode":200,"statusMessage":"OK"}}`

**Comment by martin-fleck-at** [comment]
@davidxwwang It looks to me like you are using an XML resource and not an XMI resource, so maybe there are some adaptations necessary in the encoding step. The encoding is performed by the [codecs manager](https://github.com/eclipse-emfcloud/emfcloud-modelserver/blob/c62bcea4092db4ceac2a398a93041b26cecdaf9e/bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/codecs/DICodecsManager.java) depending on the requested format and by default we [bind](https://github.com/eclipse-emfcloud/emfcloud-modelserver/blob/f28bfbe5fd070125939a1cf65d30f42405e861b9/bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/di/MultiBindingDefaults.java#L51) the [JsonCodec](https://github.com/eclipse-emfcloud/emfcloud-modelserver/blob/27fecb03a73e323abcd8ce90a71b3935ae704b49/bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/codecs/JsonCodec.java) which uses the object mapper from Javalin. So maybe there needs to be some configuration for your resource. The whole mapping is based on [EMF JSON-Jackson](https://github.com/eclipse-emfcloud/emfjson-jackson) and [Jackson](https://github.com/FasterXML/jackson). 

Just as an example on how it all works you can see how the coffee editor [registers](https://github.com/eclipse-emfcloud/coffee-editor/blob/ca736b534c84fd692b8059b9547553ec47fba369/backend/plugins/org.eclipse.emfcloud.coffee.modelserver/src/org/eclipse/emfcloud/coffee/modelserver/CoffeeModelServerModule.java#L39) its own codec and overrides the default codec for Json to [another implementation](https://github.com/eclipse-emfcloud/coffee-editor/blob/ca736b534c84fd692b8059b9547553ec47fba369/backend/plugins/org.eclipse.emfcloud.coffee.modelserver/src/org/eclipse/emfcloud/coffee/modelserver/CoffeeModelServerModule.java#L39).

Hopefully this will help you solve your problem.
