### ISSUE TITLE
ModelServer API v2

### ISSUE THREAD

**Issue by sdirix** [eclipse-emfcloud/emfcloud-modelserver#150]
The current ModelServer API often directly serializes EMF Objects to JSON and directly exposed the EMF command stack and change notifications. Going forward it would be nice to ensure the technology independence of the API, in particular removing nomenclature, syntax, and structures that are biased to the Eclipse Modeling Framework (EMF). This would help to remove barriers to implementation of client applications and server components in Javascript and other web technologies.

We therefore suggest developing a version 2 of the API which is more convenient for Javascript clients but also keeps the current benefits for Java clients.

**Comment by martin-fleck-at** [comment]
Hi Stefan,

Great idea! I agree that there are a few areas that definitely need improving (e.g., change notifications as discussed in https://github.com/eclipse-emfcloud/emfcloud-modelserver/issues/79) and I like the idea of a version 2. It'd definitely help us get a cleaner API with all the experience and use cases we have collected during development of v1 without breaking existing clients. I also think removing the EMF nomenclature from the API is a good idea as it reveals more about the implementation than about the functionality. So I think this is a great chance for us, as long as Java clients are still fully supported and provide the benefits we currently have using EMF more or less directly.

With regards to v1, the most important part for me is that it still works as it does now to avoid forcing people to update. Any new functionality, however, does not need to be back ported in my opinion. Also, we should consider a clear and detailed documentation for v2 and provide a guide that details how adopters can migrate from v1 to v2. If we have all that, I don't think there should be any problems with providing a v2.
