### ISSUE TITLE
Create 0.8.0 stable release

### ISSUE THREAD

**Issue by martin-fleck-at** [eclipse-emfcloud/emfcloud-modelserver#153]
Mandatory remaining tickets:
- [ ] https://github.com/eclipse-emfcloud/emfcloud-modelserver-theia/issues/61 
- [x] https://github.com/eclipse-emfcloud/emfcloud-modelserver-theia/issues/65
- [ ] https://github.com/eclipse-emfcloud/emfcloud-modelserver-theia/issues/76
- [x] https://github.com/eclipse-emfcloud/emfcloud-modelserver-theia/issues/73
- [x] https://github.com/eclipse-emfcloud/emfcloud-modelserver-theia/issues/96
- [x] #148 
- [ ] #139  
- [ ] #166 
- [ ] #167
- [x] #200 

Optional tickets:
- [ ] https://github.com/eclipse-emfcloud/emfcloud-modelserver-theia/issues/52
- [x] https://github.com/eclipse-emfcloud/emfcloud-modelserver/issues/144
- [ ] https://github.com/eclipse-emfcloud/emfcloud-modelserver/issues/132

**Comment by ndoschek** [comment]
I added the two issues #144 and #148 to update dependencies in the list of tickets

**Comment by ndoschek** [comment]
Close in favor of Milestone https://github.com/eclipse-emfcloud/emfcloud-modelserver/milestone/1
