### ISSUE TITLE
GetAll Method from the ModelServerClient.java does not return our models

### ISSUE THREAD

**Issue by NomsaT** [eclipse-emfcloud/emfcloud-modelserver#156]
Currently trying to access all the models from our workspace using java API but the getAll method returns an empty list + some warnings in the console indicating that the models are incomplete. By calling the API directly from Postman, it retrieves all models without problem.
Does anyone know if our models need to be in a specific format for them to be "complete" because from our observations the two conditions for the if statement inside the getAll method are false( i.modelUri.isPresent() && content.isPresent()) and we are not sure why this is the case.

**Comment by vhemery** [comment]
I made a rapid guess analysis on https://github.com/eclipse-emfcloud/emfcloud/discussions/113
To be confirmed...

**Comment by martin-fleck-at** [comment]
@NomsaT Thank you very much for reporting this! This is indeed a wrong implementation in the Java ModelServerClient, I'll provide a fix for it soon. The Theia client uses the [correct parsing method](https://github.com/eclipse-emfcloud/emfcloud-modelserver-theia/blob/79b6e7b1acd705f42daebd5487de765bf4a15588/packages/modelserver-client/src/utils/type-util.ts#L141).

@vhemery Thank you for providing such a quick response and analysis! This really helped to narrow down the problem a lot.

**Comment by ndoschek** [comment]
Closed via #164
