### ISSUE TITLE
Use injectable object mapper

### ISSUE THREAD

**Issue by martin-fleck-at** [eclipse-emfcloud/emfcloud-modelserver#171]
We seemingly bind it the object mapper in the DefaultModelServerModule using ProviderDefaults.provideObjectMapper() but we never actually inject the mapper somewhere. Instead, we always use the default object mapper instead. For some cases that makes sense since we are providing static methods, e.g., the JsonCodec., but even those should probably be factored out into a dedicated service or something similar.

**Comment by ndoschek** [comment]
This is obsolete now, as for example validation dynamically adds the resource to allow for id mapping.
Hence, a new object mapper is needed each time as the resource might change.

See https://github.com/eclipse-emfcloud/emfcloud-modelserver/pull/244
