### ISSUE TITLE
Align code formatting and checkstyle settings with GLSP

### ISSUE THREAD

**Issue by martin-fleck-at** [eclipse-emfcloud/emfcloud-modelserver#19]
@tortmayr reused the codeformatting/checkstyle settings of this repo for GLSP and made some minor improvements. We should probably apply these changes here as well once the transition to the eclipse infrastructure is completed.

**Comment by tortmayr** [comment]
Maybe provide org.eclipse.emfcloud.codestyle via update-site and consume in all EMF-Cloud/GLSP repositories
