### ISSUE TITLE
Support Java 17 and update build

### ISSUE THREAD

**Issue by ndoschek** [eclipse-emfcloud/emfcloud-modelserver#211]
Support Java 17 and doublecheck:
- Jenkins build (build 11 and 17)
- GitHub action builds (build 11 and 17)
- Google Guice dependencies?
- Binary release (both or is 17 sufficient)?

**Comment by ndoschek** [comment]
Building the model server with Java 17 errors with the following output:

```
$ mvn clean verify
[ERROR] Error executing Maven.
[ERROR] java.lang.IllegalStateException: Unable to load cache item
[ERROR] Caused by: Unable to load cache item
[ERROR] Caused by: Could not initialize class com.google.inject.internal.cglib.core.$MethodWrapper
```

**Comment by eneufeld** [comment]
which maven version are we using? does it not support java 17 or something?
