### ISSUE TITLE
Support for uploading model files

### ISSUE THREAD

**Issue by AlexandraBuzila** [eclipse-emfcloud/emfcloud-modelserver#238]
Currently, all available models are loaded on startup. For some scenarios, when the models are managed outside the model server, it would make sense to provide an endpoint that can be used to upload models to the model server, e.g. `putModel` that receives the contents of a model file and loads it.

**Comment by AlexandraBuzila** [comment]
@ndoschek do you think this would be useful?

**Comment by ndoschek** [comment]
Hi @AlexandraBuzila!
Would the existing endpoint `[POST] /models` (see also https://github.com/eclipse-emfcloud/emfcloud-modelserver#http-endpoints---v2) work for this scenario as well?

**Comment by AlexandraBuzila** [comment]
Thanks @ndoschek! You're right, the `[POST] /models` endpoint does exactly that.
