### ISSUE TITLE
With command edit API, can't use SetCommand on a containment feature

### ISSUE THREAD

**Issue by vhemery** [eclipse-emfcloud/emfcloud-modelserver#257]
For the moment, when using commands, you can not create a SetCommand on a containment feature.
This is blocking https://github.com/eclipse-emfcloud/emfcloud-modelserver-theia/issues/52

A simple solution is to use the objectsToAdd property for containment features and allow it to store object values.

**Comment by ndoschek** [comment]
Closed with #258
