### ISSUE TITLE
Improve ModelServerLauncher for easier customization 

### ISSUE THREAD

**Issue by martin-fleck-at** [eclipse-emfcloud/emfcloud-modelserver#54]
Currently the model server launcher provides some methods to add customizations, e.g., `addEPackageConfigurations`. However, in other cases no such method exists, e.g., when trying to add additional routing, see [1] and [2]. I believe the API could be improved in this regard to allow easier integration of additional modules (generics in the return type of `getModules` make it unnecessarily difficult) and to already provide hooks for classes which may be implemented more than once, i.e., that have a collection binding.

I believe we could discuss whether that improved customizations should be part of the `ModelServerModule` itself or the `ModelServerLauncher`.

[1] https://spectrum.chat/emfcloud/modelserver/model-server-api-to-return-models-of-a-specific-type~b4a27e5d-48e6-41fe-8177-f66056f8c77f
[2] https://github.com/eclipse-emfcloud/emfcloud-modelserver/commit/954ffed79b78b772b9b657a80e06f88f1ded9575

**Comment by ndoschek** [comment]
Closed via #81
