### ISSUE TITLE
Unit tests failing on windows due to OS-specific constructions

### ISSUE THREAD

**Issue by vhemery** [eclipse-emfcloud/emfcloud-modelserver#64]
When executing on windows, unit tests in org.eclipse.emfcloud.modelserver.emf.tests fail. (on master branch, commit 4d383b90e46c830ffd3cff6fddd7d1e30a367376 )
![image](https://user-images.githubusercontent.com/7920847/104559508-c783ca80-5644-11eb-93d7-d82c7fdbd351.png)
Some are due to #63 , but there are other causes, most probably specific to the windows OS.

The following tests fail due to a difference in whitespaces characters (mainly "\n" vs "\r\n" line breaks) :
- org.eclipse.emfcloud.modelserver.emf.common.ModelControllerTest.getModelelementByNameXmiFormat()
- org.eclipse.emfcloud.modelserver.emf.common.ModelControllerTest.getModelelementByIdXmiFormat()
- org.eclipse.emfcloud.modelserver.emf.EMFJsonConverterTest.testToJsonSimple()
- org.eclipse.emfcloud.modelserver.emf.EMFJsonConverterTest.testToJsonCoffeeJson()
I suggest calling org.junit.platform.commons.util.StringUtils.replaceWhitespaceCharacters(String, String) when comparing strings to avoid this issue.

Some other tests fail with "java.lang.IllegalArgumentException: resolve against non-hierarchical or relative base". This is the case of :
- org.eclipse.emfcloud.modelserver.emf.common.ModelControllerTest.executeCommand()
- org.eclipse.emfcloud.modelserver.emf.common.ModelControllerTest.addCommandNotification()
We'll have to investigate more, but my first guess would be a difference of separator in constructed URIs.

Finally, these tests fail (directly or indirectly) due to differences in built URIs (difference of separator) :
- org.eclipse.emfcloud.modelserver.emf.configuration.ServerConfigurationTest.normalizeWorkspaceRoot()
- org.eclipse.emfcloud.modelserver.emf.configuration.ServerConfigurationTest.getUiSchemaFolder()
- org.eclipse.emfcloud.modelserver.emf.configuration.ServerConfigurationTest.normalizeWorkspaceRootSlashAlreadyPresent()
- org.eclipse.emfcloud.modelserver.emf.configuration.ServerConfigurationTest.setWorkspaceRoot()
- org.eclipse.emfcloud.modelserver.emf.configuration.ServerConfigurationTest.normalizeWorkspaceRootEncoded()
- org.eclipse.emfcloud.modelserver.emf.configuration.ServerConfigurationTest.getWorkspaceEntries()
And also probably (but must be confirmed by investigation) :
- org.eclipse.emfcloud.modelserver.emf.configuration.ServerConfigurationTest.isUiSchemaFolder()
- org.eclipse.emfcloud.modelserver.emf.configuration.ServerConfigurationTest.isValidFileURI()

**Comment by martin-fleck-at** [comment]
Thank you very much for bringing this to our attention! we were not aware of the OS-dependent test failures and will look at this in more detail when we are working on the overall test story (#62 , #63).
