### ISSUE TITLE
Upgrade to latest Javalin version as soon as mocking problems are resolved

### ISSUE THREAD

**Issue by martin-fleck-at** [eclipse-emfcloud/emfcloud-modelserver#74]
This is a follow-up issue from https://github.com/eclipse-emfcloud/emfcloud-modelserver/issues/63 where it was reported that in newer Javalin versions mockito *sometimes* fails when mocking Javalin classes. There are several open issues related to this:
- https://github.com/tipsy/javalin/issues/979
- https://github.com/tipsy/javalin/issues/1098
- https://github.com/mockito/mockito/issues/1943

As soon as the issues are resolved we can upgrade.

**Comment by tipsy** [comment]
Soon :)
