### ISSUE TITLE
Model edition may load and edit another resource instead of the managed one.

### ISSUE THREAD

**Issue by vhemery** [eclipse-emfcloud/emfcloud-modelserver#85]
When loading a resource, the method org.eclipse.emfcloud.modelserver.emf.common.ModelResourceManager.adaptModelUri(String) gets called for fixing the URI.
As a result, the URI is normalized, replacing (for example) `file:///d:/myModel.coffee` with `file:/d:/myModel.coffee`.

On the other hand, when creating a command, the owner's ModelServerReferenceDescription (when using uri.toString() without the skipEncoding attribute) may look like `file:///d%3A/myModel.cofee#...` which, after json decoding and EMF resolution, gives a model element from resource with URI `file:///d%3A/myModel.cofee`.

The direct consequence is that the new resource is loaded and edited (in the same resource set) while the previously loaded resource is not edited. When loading element back, I hence get the original element from the non-edited resource. 
Note that there may also be OS-specific factors here...

I've identified 3 ways of fixing it :
- the easiest (and dirtiest) : on the front side, by using a ModelServerReferenceDescription with the normalized URI (knowing the server implementation).
- using a fixed URIHandler (which calls adaptModelUri) during json parsing (IMHO the best option, but not the easiest). This uri handler must be set on org.emfjson.jackson.module.EMFModule before setting up the mapper, and in this case, we must no longer call `org.emfjson.jackson.module.EMFModule.setupDefaultMapper(JsonFactory)` (directly or indirectly), which use a new EMFModule. (note by the way that we do not always use the ObjectMapper bound by ModelServerModule in controllers implementations, and this looks intended...)
- by setting a URIConverter on the resource set which will adapt the model URI before loading the resource. (the difficulty is not to have conflicts with a user-custom URIConverter on the resource set)

For now, I've successfully used the 1st fix as a workaround to edit my models.

**Comment by ndoschek** [comment]
Hi @vhemery, with the updates regarding model URI handling along with `v2`, could this issue be resolved for you? TIA for any feedback

**Comment by vhemery** [comment]
Should be fixed by now with URI refactorings.
And I no longer have the sources to reproduce...
