### ISSUE TITLE
Command.ecore uses 'http://www.eclipsesource.com/schema/2019/modelserver/command' as Namespace URI

### ISSUE THREAD

**Issue by martin-fleck-at** [eclipse-emfcloud/emfcloud-modelserver#87]
I wonder if the namespace URI for commands should be updated to something else.

**Comment by ndoschek** [comment]
Great idea! Maybe we can use a similar nsUri as the currently to-be-extracted coffee model (PR https://github.com/eclipse-emfcloud/coffee-editor/pull/334 is currently in review).
Maybe something like `"http://www.eclipse.org/emfcloud/modelserver/command"` (+ maybe some versioning indicator?)
