### ISSUE TITLE
Drop coffee model package and replace examples

### ISSUE THREAD

**Issue by ndoschek** [eclipse-emfcloud/emfcloud-modelserver#88]
There is currently a PR ongoing to extract the coffee model definition and integrate it directly into the coffee-editor (see https://github.com/eclipse-emfcloud/coffee-editor/pull/334/files).
Therefore I think it would make sense to drop the `org.eclipse.emfcloud.modelserver.coffee.model` package and consume it from the coffee editor if we want to keep the coffee examples.

**Comment by tortmayr** [comment]
:+1:  for dropping the `org.eclipse.emfcloud.modelserver.coffee.model` package. However, I think it makes sense that the modelserver repository is self-contained. The tests not necessarily need the coffee model and could operate on plain .ecore models instead. IMO we should avoid cross-repository dependencies and only rely on them if absolutely necessary.

**Comment by ndoschek** [comment]
That's a good point, thanks for your input! I updated the issue title :+1:

**Comment by martin-fleck-at** [comment]
I believe the unit tests already do not build on top of the coffee model. They do have a `Coffee.ecore` in there but only use it as an example Ecore model and nothing specific from that package is needed. So for the unit tests we could already remove that package and be happy.

However, our runtime example where we provide a specific model server implementation use case is built on top of the coffee model, i.e., we showcase how to register your ecore model for the model server and how to implement custom commands using generated EMF API. That is also the reason why this package is in the "examples" folder and not in the normal "bundles" and why it is also not part of the generated p2 update site. It might be that we still publish the example (and coffee model) to the maven repository which we can probably skip.

So I am not sure how we should proceed here. As @tortmayr correctly said, the model server repository should definitely stay self-contained so I'd rather not import the example model from somewhere else. If we want to avoid confusion with the coffee editor we provide our example based on another metamodel but I'm not sure this is necessary.

@tortmayr @ndoschek What do you think?

**Comment by martin-fleck-at** [comment]
I think all the necessary changes have been addressed and the modelserver repository is self-contained now.
