### ISSUE TITLE
Client should support create call

### ISSUE THREAD

**Issue by martin-fleck-at** [eclipse-emfcloud/emfcloud-modelserver#9]

**Comment by cbos** [comment]
@martin-fleck-at 
I was looking in the way to create new models through the client API, both the client and the REST API.
I found that the create option in the client API is missing as defined in this ticket.

What should the method name and signature look like? I probably can add it and raise a pull request. 
Currently it is missing in the API.

Should it be possible to just create an empty model, like you in an IDE do new .. file .. and save that empty file?

When I do POST http://localhost:8081/api/v1/models?modeluri=test.coffee I get a NullPointerException as there is no JSON at all. 
But even when I provide an JSON object it still refuses it with the message "Create new model failed", internal message is Empty JSON.

It looks like the create flow requires some fine tuning.
